### ISSUE TITLE
Has Crtl + C been dispbled?

### ISSUE THREAD

**Issue by coatsy35** [Courseplay/ClickToSwitch#8]
I can only right click to view mouse pointer (which is a pain when using loaders) Ctrl_C does not disable it and switch to the alternative mode? the pictures on the mod show a different menu which I don't see. on FS22

**Comment by Tensuko** [comment]
That function is only for non CP user.
With CP you got to turn off open hud with mouse in the vehicle settings.
With only CTS, you have the keybinds available.
